# Generated by Django 4.2.2 on 2023-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_alter_arrow_arrow_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrow',
            name='arrow_image',
            field=models.ImageField(default='images/arrow_up.gif', upload_to=''),
        ),
    ]
