# Generated by Django 4.2.2 on 2023-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_alter_arrow_arrow_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level_image',
            new_name='image',
        ),
    ]
