# Generated by Django 4.2.2 on 2023-07-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_alter_level_level_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level_image',
            new_name='image',
        ),
    ]
