# Generated by Django 4.2.2 on 2023-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_rename_level_image_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, default='images/floor10.png', upload_to=''),
        ),
    ]
