# Generated by Django 4.2.2 on 2023-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0014_alter_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(default='images/floor10.png', upload_to=''),
        ),
    ]
